### ISSUE TITLE
Meer documentatie over sensor types

### ISSUE THREAD

**Issue by SampersS** [vives-project-xp/GreenhouseNetwork-Monitoring#74]
Ik moet kiezen voor een sensor type (MAAAR!) ik weet niet wat de maximuum en minimuum waarden zijn per sensor type of waar ik dat handmatig kan instellen.

Documenteer dat of zeg mischien als er een maximuum waarde globaal is.

**Comment by imawizzard** [comment]
Battery Level type is toegevoegd.

Je bent nu verplicht om bij de sensor een minimum en maximum mee te geven

```c++
  sensor = HaSensor("Temperature", SensorType::TEMPERATURE, -20, 30);
```
